# Example Pepys configuration
port = 8088
username = "admin"
password = "password123"

# The test RTSP server, and the default
rtsp_server_command = "live555MediaServer"

# The RTSP server for the Raspberry Pi
#rtsp_server_command = "v4l2rtspserver -P 8554 -u h264 -W 1280 -H 720 /dev/video0"