// Generated by ./build_scripts/gen_code.pl from ./schemata/event.wsdl ---------------------
use yaserde_derive::*;
use soapenv::Header;

#[derive(Debug, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
    namespace = "tds: http://www.onvif.org/ver10/device/wsdl"
)]
pub struct Envelope {
    #[yaserde(prefix = "s", rename = "Header")]
    pub header: Option<Header>,

    #[yaserde(prefix = "s", rename = "Body")]
    pub body: Body,
}

#[derive(Debug, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
)]
pub enum Body {
    Unknown, // Requirement of `Default` impl, required by YaDeserialize

        #[yaserde(prefix = "tds")]
    AddEventBroker(super::AddEventBroker),

    #[yaserde(prefix = "tds")]
    CreatePullPointSubscription(super::CreatePullPointSubscription),

    #[yaserde(prefix = "tds")]
    DeleteEventBroker(super::DeleteEventBroker),

    #[yaserde(prefix = "tds")]
    GetEventBrokers(super::GetEventBrokers),

    #[yaserde(prefix = "tds")]
    GetEventProperties(super::GetEventProperties),

    #[yaserde(prefix = "tds")]
    GetServiceCapabilities(super::GetServiceCapabilities),

    #[yaserde(prefix = "tds")]
    PullMessages(super::PullMessages),

    #[yaserde(prefix = "tds")]
    Seek(super::Seek),

    #[yaserde(prefix = "tds")]
    SetSynchronizationPoint(super::SetSynchronizationPoint),

    // #[yaserde(prefix = "tds")]
    // Unsubscribe(super::Unsubscribe) -- TODO: why is this struct definition absent?
}

impl Default for Body {
    fn default() -> Self {
        Body::Unknown
    }
}
