// Generated by ./build_scripts/gen_code.pl from ./schemata/event.wsdl ---------------------
use yaserde_derive::*;

#[derive(Debug, YaSerialize, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
    namespace = "tds: http://www.onvif.org/ver10/device/wsdl"
)]
pub struct Envelope {
    #[yaserde(prefix = "s", rename = "Body")]
    pub body: Body,
}

#[derive(Debug, YaSerialize, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
    namespace = "tds: http://www.onvif.org/ver10/device/wsdl",
    namespace = "tev: http://www.onvif.org/ver10/events/wsdl",
    namespace = "wsnt: http://docs.oasis-open.org/wsn/b-2"
)]
pub enum Body {
    Unknown, // Requirement of `Default` impl, required by YaDeserialize

    #[yaserde(prefix = "tev")]
	AddEventBrokerResponse(super::AddEventBrokerResponse),
	#[yaserde(prefix = "tev")]
	CreatePullPointSubscriptionResponse(super::CreatePullPointSubscriptionResponse),
	#[yaserde(prefix = "tev")]
	DeleteEventBrokerResponse(super::DeleteEventBrokerResponse),
	#[yaserde(prefix = "tev")]
	GetEventBrokersResponse(super::GetEventBrokersResponse),
	#[yaserde(prefix = "tev")]
	GetEventPropertiesResponse(super::GetEventPropertiesResponse),
	#[yaserde(prefix = "tev")]
	GetServiceCapabilitiesResponse(super::GetServiceCapabilitiesResponse),
	#[yaserde(prefix = "tev")]
	PullMessagesResponse(super::PullMessagesResponse),
	#[yaserde(prefix = "tev")]
	SeekResponse(super::SeekResponse),
	#[yaserde(prefix = "tev")]
	SetSynchronizationPointResponse(super::SetSynchronizationPointResponse),
	// #[yaserde(prefix = "tev")]
	// UnsubscribeResponse(super::UnsubscribeResponse) -- TODO: why is this struct definition absent?
}

impl Default for Body {
    fn default() -> Self {
        Body::Unknown
    }
}
