// Generated by ./build_scripts/gen_code.pl from ./schemata/event.wsdl ---------------------
use yaserde_derive::*;

#[derive(Debug, YaSerialize, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
    namespace = "tds: http://www.onvif.org/ver10/device/wsdl"
)]
pub struct Envelope {
    #[yaserde(prefix = "s", rename = "Body")]
    pub body: Body,
}

#[derive(Debug, YaSerialize, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
    namespace = "tds: http://www.onvif.org/ver10/device/wsdl"
)]
pub enum Body {
    Unknown, // Requirement of `Default` impl, required by YaDeserialize

    #[yaserde(prefix = "tds")]
	AddEventBrokerResponse(super::AddEventBrokerResponse),
	#[yaserde(prefix = "tds")]
	CreatePullPointSubscriptionResponse(super::CreatePullPointSubscriptionResponse),
	#[yaserde(prefix = "tds")]
	DeleteEventBrokerResponse(super::DeleteEventBrokerResponse),
	#[yaserde(prefix = "tds")]
	GetEventBrokersResponse(super::GetEventBrokersResponse),
	#[yaserde(prefix = "tds")]
	GetEventPropertiesResponse(super::GetEventPropertiesResponse),
	#[yaserde(prefix = "tds")]
	GetServiceCapabilitiesResponse(super::GetServiceCapabilitiesResponse),
	#[yaserde(prefix = "tds")]
	PullMessagesResponse(super::PullMessagesResponse),
	#[yaserde(prefix = "tds")]
	SeekResponse(super::SeekResponse),
	#[yaserde(prefix = "tds")]
	SetSynchronizationPointResponse(super::SetSynchronizationPointResponse),
	#[yaserde(prefix = "tds")]
	UnsubscribeResponse(super::UnsubscribeResponse)
}

impl Default for Body {
    fn default() -> Self {
        Body::Unknown
    }
}

