[package]
name = "xml-to-rs"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
media = {path = "../../wsdl_rs/media"}
onvif = {path = "../../xsd_rs/onvif"}

yaserde = "0.7.1"
yaserde_derive = "0.7.1"
