[package]
name = "xml-to-rs"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
media = {path = "../../wsdl_rs/media"}
onvif = {path = "../../xsd_rs/onvif"}

yaserde.workspace = true
yaserde_derive.workspace = true
