[package]
name = "integration_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.0"
reqwest = {version = "0.11.13", features = ["blocking"]}
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
path_macro = "1.0"
lazy_static = "1.4.0"
