// Generated by ./build_scripts/gen_code.pl from ./schemata/media.wsdl.xml ---------------------
use yaserde_derive::*;
use soapenv::Header;

#[derive(Debug, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
    namespace = "tds: http://www.onvif.org/ver10/device/wsdl"
)]
pub struct Envelope {
    #[yaserde(prefix = "s", rename = "Header")]
    pub header: Option<Header>,

    #[yaserde(prefix = "s", rename = "Body")]
    pub body: Body,
}

#[derive(Debug, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
)]
pub enum Body {
    Unknown, // Requirement of `Default` impl, required by YaDeserialize

        #[yaserde(prefix = "tds")]
    AddAudioDecoderConfiguration(super::AddAudioDecoderConfiguration),

    #[yaserde(prefix = "tds")]
    AddAudioEncoderConfiguration(super::AddAudioEncoderConfiguration),

    #[yaserde(prefix = "tds")]
    AddAudioOutputConfiguration(super::AddAudioOutputConfiguration),

    #[yaserde(prefix = "tds")]
    AddAudioSourceConfiguration(super::AddAudioSourceConfiguration),

    #[yaserde(prefix = "tds")]
    AddMetadataConfiguration(super::AddMetadataConfiguration),

    #[yaserde(prefix = "tds")]
    AddPTZConfiguration(super::AddPTZConfiguration),

    #[yaserde(prefix = "tds")]
    AddVideoAnalyticsConfiguration(super::AddVideoAnalyticsConfiguration),

    #[yaserde(prefix = "tds")]
    AddVideoEncoderConfiguration(super::AddVideoEncoderConfiguration),

    #[yaserde(prefix = "tds")]
    AddVideoSourceConfiguration(super::AddVideoSourceConfiguration),

    #[yaserde(prefix = "tds")]
    CreateOSD(super::CreateOSD),

    #[yaserde(prefix = "tds")]
    CreateProfile(super::CreateProfile),

    #[yaserde(prefix = "tds")]
    DeleteOSD(super::DeleteOSD),

    #[yaserde(prefix = "tds")]
    DeleteProfile(super::DeleteProfile),

    #[yaserde(prefix = "tds")]
    GetAudioDecoderConfiguration(super::GetAudioDecoderConfiguration),

    #[yaserde(prefix = "tds")]
    GetAudioDecoderConfigurationOptions(super::GetAudioDecoderConfigurationOptions),

    #[yaserde(prefix = "tds")]
    GetAudioDecoderConfigurations(super::GetAudioDecoderConfigurations),

    #[yaserde(prefix = "tds")]
    GetAudioEncoderConfiguration(super::GetAudioEncoderConfiguration),

    #[yaserde(prefix = "tds")]
    GetAudioEncoderConfigurationOptions(super::GetAudioEncoderConfigurationOptions),

    #[yaserde(prefix = "tds")]
    GetAudioEncoderConfigurations(super::GetAudioEncoderConfigurations),

    #[yaserde(prefix = "tds")]
    GetAudioOutputConfiguration(super::GetAudioOutputConfiguration),

    #[yaserde(prefix = "tds")]
    GetAudioOutputConfigurationOptions(super::GetAudioOutputConfigurationOptions),

    #[yaserde(prefix = "tds")]
    GetAudioOutputConfigurations(super::GetAudioOutputConfigurations),

    #[yaserde(prefix = "tds")]
    GetAudioOutputs(super::GetAudioOutputs),

    #[yaserde(prefix = "tds")]
    GetAudioSourceConfiguration(super::GetAudioSourceConfiguration),

    #[yaserde(prefix = "tds")]
    GetAudioSourceConfigurationOptions(super::GetAudioSourceConfigurationOptions),

    #[yaserde(prefix = "tds")]
    GetAudioSourceConfigurations(super::GetAudioSourceConfigurations),

    #[yaserde(prefix = "tds")]
    GetAudioSources(super::GetAudioSources),

    #[yaserde(prefix = "tds")]
    GetCompatibleAudioDecoderConfigurations(super::GetCompatibleAudioDecoderConfigurations),

    #[yaserde(prefix = "tds")]
    GetCompatibleAudioEncoderConfigurations(super::GetCompatibleAudioEncoderConfigurations),

    #[yaserde(prefix = "tds")]
    GetCompatibleAudioOutputConfigurations(super::GetCompatibleAudioOutputConfigurations),

    #[yaserde(prefix = "tds")]
    GetCompatibleAudioSourceConfigurations(super::GetCompatibleAudioSourceConfigurations),

    #[yaserde(prefix = "tds")]
    GetCompatibleMetadataConfigurations(super::GetCompatibleMetadataConfigurations),

    #[yaserde(prefix = "tds")]
    GetCompatibleVideoAnalyticsConfigurations(super::GetCompatibleVideoAnalyticsConfigurations),

    #[yaserde(prefix = "tds")]
    GetCompatibleVideoEncoderConfigurations(super::GetCompatibleVideoEncoderConfigurations),

    #[yaserde(prefix = "tds")]
    GetCompatibleVideoSourceConfigurations(super::GetCompatibleVideoSourceConfigurations),

    #[yaserde(prefix = "tds")]
    GetGuaranteedNumberOfVideoEncoderInstances(super::GetGuaranteedNumberOfVideoEncoderInstances),

    #[yaserde(prefix = "tds")]
    GetMetadataConfiguration(super::GetMetadataConfiguration),

    #[yaserde(prefix = "tds")]
    GetMetadataConfigurationOptions(super::GetMetadataConfigurationOptions),

    #[yaserde(prefix = "tds")]
    GetMetadataConfigurations(super::GetMetadataConfigurations),

    #[yaserde(prefix = "tds")]
    GetOSD(super::GetOSD),

    #[yaserde(prefix = "tds")]
    GetOSDOptions(super::GetOSDOptions),

    #[yaserde(prefix = "tds")]
    GetOSDs(super::GetOSDs),

    #[yaserde(prefix = "tds")]
    GetProfile(super::GetProfile),

    #[yaserde(prefix = "tds")]
    GetProfiles(super::GetProfiles),

    #[yaserde(prefix = "tds")]
    GetServiceCapabilities(super::GetServiceCapabilities),

    #[yaserde(prefix = "tds")]
    GetSnapshotUri(super::GetSnapshotUri),

    #[yaserde(prefix = "tds")]
    GetStreamUri(super::GetStreamUri),

    #[yaserde(prefix = "tds")]
    GetVideoAnalyticsConfiguration(super::GetVideoAnalyticsConfiguration),

    #[yaserde(prefix = "tds")]
    GetVideoAnalyticsConfigurations(super::GetVideoAnalyticsConfigurations),

    #[yaserde(prefix = "tds")]
    GetVideoEncoderConfiguration(super::GetVideoEncoderConfiguration),

    #[yaserde(prefix = "tds")]
    GetVideoEncoderConfigurationOptions(super::GetVideoEncoderConfigurationOptions),

    #[yaserde(prefix = "tds")]
    GetVideoEncoderConfigurations(super::GetVideoEncoderConfigurations),

    #[yaserde(prefix = "tds")]
    GetVideoSourceConfiguration(super::GetVideoSourceConfiguration),

    #[yaserde(prefix = "tds")]
    GetVideoSourceConfigurationOptions(super::GetVideoSourceConfigurationOptions),

    #[yaserde(prefix = "tds")]
    GetVideoSourceConfigurations(super::GetVideoSourceConfigurations),

    #[yaserde(prefix = "tds")]
    GetVideoSourceModes(super::GetVideoSourceModes),

    #[yaserde(prefix = "tds")]
    GetVideoSources(super::GetVideoSources),

    #[yaserde(prefix = "tds")]
    RemoveAudioDecoderConfiguration(super::RemoveAudioDecoderConfiguration),

    #[yaserde(prefix = "tds")]
    RemoveAudioEncoderConfiguration(super::RemoveAudioEncoderConfiguration),

    #[yaserde(prefix = "tds")]
    RemoveAudioOutputConfiguration(super::RemoveAudioOutputConfiguration),

    #[yaserde(prefix = "tds")]
    RemoveAudioSourceConfiguration(super::RemoveAudioSourceConfiguration),

    #[yaserde(prefix = "tds")]
    RemoveMetadataConfiguration(super::RemoveMetadataConfiguration),

    #[yaserde(prefix = "tds")]
    RemovePTZConfiguration(super::RemovePTZConfiguration),

    #[yaserde(prefix = "tds")]
    RemoveVideoAnalyticsConfiguration(super::RemoveVideoAnalyticsConfiguration),

    #[yaserde(prefix = "tds")]
    RemoveVideoEncoderConfiguration(super::RemoveVideoEncoderConfiguration),

    #[yaserde(prefix = "tds")]
    RemoveVideoSourceConfiguration(super::RemoveVideoSourceConfiguration),

    #[yaserde(prefix = "tds")]
    SetAudioDecoderConfiguration(super::SetAudioDecoderConfiguration),

    #[yaserde(prefix = "tds")]
    SetAudioEncoderConfiguration(super::SetAudioEncoderConfiguration),

    #[yaserde(prefix = "tds")]
    SetAudioOutputConfiguration(super::SetAudioOutputConfiguration),

    #[yaserde(prefix = "tds")]
    SetAudioSourceConfiguration(super::SetAudioSourceConfiguration),

    #[yaserde(prefix = "tds")]
    SetMetadataConfiguration(super::SetMetadataConfiguration),

    #[yaserde(prefix = "tds")]
    SetOSD(super::SetOSD),

    #[yaserde(prefix = "tds")]
    SetSynchronizationPoint(super::SetSynchronizationPoint),

    #[yaserde(prefix = "tds")]
    SetVideoAnalyticsConfiguration(super::SetVideoAnalyticsConfiguration),

    #[yaserde(prefix = "tds")]
    SetVideoEncoderConfiguration(super::SetVideoEncoderConfiguration),

    #[yaserde(prefix = "tds")]
    SetVideoSourceConfiguration(super::SetVideoSourceConfiguration),

    #[yaserde(prefix = "tds")]
    SetVideoSourceMode(super::SetVideoSourceMode),

    #[yaserde(prefix = "tds")]
    StartMulticastStreaming(super::StartMulticastStreaming),

    #[yaserde(prefix = "tds")]
    StopMulticastStreaming(super::StopMulticastStreaming)
}

impl Default for Body {
    fn default() -> Self {
        Body::Unknown
    }
}
