// Generated by ./build_scripts/gen_code.pl from ./schemata/media.wsdl.xml ---------------------
use yaserde_derive::*;

#[derive(Debug, YaSerialize, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
    namespace = "tds: http://www.onvif.org/ver10/device/wsdl"
)]
pub struct Envelope {
    #[yaserde(prefix = "s", rename = "Body")]
    pub body: Body,
}

#[derive(Debug, YaSerialize, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
)]
pub enum Body {
    Unknown, // Requirement of `Default` impl, required by YaDeserialize

    AddAudioDecoderConfigurationResponse(super::AddAudioDecoderConfigurationResponse),
	AddAudioEncoderConfigurationResponse(super::AddAudioEncoderConfigurationResponse),
	AddAudioOutputConfigurationResponse(super::AddAudioOutputConfigurationResponse),
	AddAudioSourceConfigurationResponse(super::AddAudioSourceConfigurationResponse),
	AddMetadataConfigurationResponse(super::AddMetadataConfigurationResponse),
	AddPTZConfigurationResponse(super::AddPTZConfigurationResponse),
	AddVideoAnalyticsConfigurationResponse(super::AddVideoAnalyticsConfigurationResponse),
	AddVideoEncoderConfigurationResponse(super::AddVideoEncoderConfigurationResponse),
	AddVideoSourceConfigurationResponse(super::AddVideoSourceConfigurationResponse),
	CreateOSDResponse(super::CreateOSDResponse),
	CreateProfileResponse(super::CreateProfileResponse),
	DeleteOSDResponse(super::DeleteOSDResponse),
	DeleteProfileResponse(super::DeleteProfileResponse),
	GetAudioDecoderConfigurationOptionsResponse(super::GetAudioDecoderConfigurationOptionsResponse),
	GetAudioDecoderConfigurationResponse(super::GetAudioDecoderConfigurationResponse),
	GetAudioDecoderConfigurationsResponse(super::GetAudioDecoderConfigurationsResponse),
	GetAudioEncoderConfigurationOptionsResponse(super::GetAudioEncoderConfigurationOptionsResponse),
	GetAudioEncoderConfigurationResponse(super::GetAudioEncoderConfigurationResponse),
	GetAudioEncoderConfigurationsResponse(super::GetAudioEncoderConfigurationsResponse),
	GetAudioOutputConfigurationOptionsResponse(super::GetAudioOutputConfigurationOptionsResponse),
	GetAudioOutputConfigurationResponse(super::GetAudioOutputConfigurationResponse),
	GetAudioOutputConfigurationsResponse(super::GetAudioOutputConfigurationsResponse),
	GetAudioOutputsResponse(super::GetAudioOutputsResponse),
	GetAudioSourceConfigurationOptionsResponse(super::GetAudioSourceConfigurationOptionsResponse),
	GetAudioSourceConfigurationResponse(super::GetAudioSourceConfigurationResponse),
	GetAudioSourceConfigurationsResponse(super::GetAudioSourceConfigurationsResponse),
	GetAudioSourcesResponse(super::GetAudioSourcesResponse),
	GetCompatibleAudioDecoderConfigurationsResponse(super::GetCompatibleAudioDecoderConfigurationsResponse),
	GetCompatibleAudioEncoderConfigurationsResponse(super::GetCompatibleAudioEncoderConfigurationsResponse),
	GetCompatibleAudioOutputConfigurationsResponse(super::GetCompatibleAudioOutputConfigurationsResponse),
	GetCompatibleAudioSourceConfigurationsResponse(super::GetCompatibleAudioSourceConfigurationsResponse),
	GetCompatibleMetadataConfigurationsResponse(super::GetCompatibleMetadataConfigurationsResponse),
	GetCompatibleVideoAnalyticsConfigurationsResponse(super::GetCompatibleVideoAnalyticsConfigurationsResponse),
	GetCompatibleVideoEncoderConfigurationsResponse(super::GetCompatibleVideoEncoderConfigurationsResponse),
	GetCompatibleVideoSourceConfigurationsResponse(super::GetCompatibleVideoSourceConfigurationsResponse),
	GetGuaranteedNumberOfVideoEncoderInstancesResponse(super::GetGuaranteedNumberOfVideoEncoderInstancesResponse),
	GetMetadataConfigurationOptionsResponse(super::GetMetadataConfigurationOptionsResponse),
	GetMetadataConfigurationResponse(super::GetMetadataConfigurationResponse),
	GetMetadataConfigurationsResponse(super::GetMetadataConfigurationsResponse),
	GetOSDOptionsResponse(super::GetOSDOptionsResponse),
	GetOSDResponse(super::GetOSDResponse),
	GetOSDsResponse(super::GetOSDsResponse),
	GetProfileResponse(super::GetProfileResponse),
	GetProfilesResponse(super::GetProfilesResponse),
	GetServiceCapabilitiesResponse(super::GetServiceCapabilitiesResponse),
	GetSnapshotUriResponse(super::GetSnapshotUriResponse),
	GetStreamUriResponse(super::GetStreamUriResponse),
	GetVideoAnalyticsConfigurationResponse(super::GetVideoAnalyticsConfigurationResponse),
	GetVideoAnalyticsConfigurationsResponse(super::GetVideoAnalyticsConfigurationsResponse),
	GetVideoEncoderConfigurationOptionsResponse(super::GetVideoEncoderConfigurationOptionsResponse),
	GetVideoEncoderConfigurationResponse(super::GetVideoEncoderConfigurationResponse),
	GetVideoEncoderConfigurationsResponse(super::GetVideoEncoderConfigurationsResponse),
	GetVideoSourceConfigurationOptionsResponse(super::GetVideoSourceConfigurationOptionsResponse),
	GetVideoSourceConfigurationResponse(super::GetVideoSourceConfigurationResponse),
	GetVideoSourceConfigurationsResponse(super::GetVideoSourceConfigurationsResponse),
	GetVideoSourceModesResponse(super::GetVideoSourceModesResponse),
	GetVideoSourcesResponse(super::GetVideoSourcesResponse),
	RemoveAudioDecoderConfigurationResponse(super::RemoveAudioDecoderConfigurationResponse),
	RemoveAudioEncoderConfigurationResponse(super::RemoveAudioEncoderConfigurationResponse),
	RemoveAudioOutputConfigurationResponse(super::RemoveAudioOutputConfigurationResponse),
	RemoveAudioSourceConfigurationResponse(super::RemoveAudioSourceConfigurationResponse),
	RemoveMetadataConfigurationResponse(super::RemoveMetadataConfigurationResponse),
	RemovePTZConfigurationResponse(super::RemovePTZConfigurationResponse),
	RemoveVideoAnalyticsConfigurationResponse(super::RemoveVideoAnalyticsConfigurationResponse),
	RemoveVideoEncoderConfigurationResponse(super::RemoveVideoEncoderConfigurationResponse),
	RemoveVideoSourceConfigurationResponse(super::RemoveVideoSourceConfigurationResponse),
	SetAudioDecoderConfigurationResponse(super::SetAudioDecoderConfigurationResponse),
	SetAudioEncoderConfigurationResponse(super::SetAudioEncoderConfigurationResponse),
	SetAudioOutputConfigurationResponse(super::SetAudioOutputConfigurationResponse),
	SetAudioSourceConfigurationResponse(super::SetAudioSourceConfigurationResponse),
	SetMetadataConfigurationResponse(super::SetMetadataConfigurationResponse),
	SetOSDResponse(super::SetOSDResponse),
	SetSynchronizationPointResponse(super::SetSynchronizationPointResponse),
	SetVideoAnalyticsConfigurationResponse(super::SetVideoAnalyticsConfigurationResponse),
	SetVideoEncoderConfigurationResponse(super::SetVideoEncoderConfigurationResponse),
	SetVideoSourceConfigurationResponse(super::SetVideoSourceConfigurationResponse),
	SetVideoSourceModeResponse(super::SetVideoSourceModeResponse),
	StartMulticastStreamingResponse(super::StartMulticastStreamingResponse),
	StopMulticastStreamingResponse(super::StopMulticastStreamingResponse)
}


impl Default for Body {
    fn default() -> Self {
        Body::Unknown
    }
}
