// Generated by ./build_scripts/gen_code.pl from ./schemata/devicemgmt.wsdl.xml ---------------------
use yaserde_derive::*;

#[derive(Debug, YaSerialize, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
    namespace = "tds: http://www.onvif.org/ver10/device/wsdl"
)]
pub struct Envelope {
    #[yaserde(prefix = "s", rename = "Body")]
    pub body: Body,
}

#[derive(Debug, YaSerialize, YaDeserialize)]
#[yaserde(
    prefix = "s",
    namespace = "s: http://www.w3.org/2003/05/soap-envelope",
    namespace = "tds: http://www.onvif.org/ver10/device/wsdl"
)]
pub enum Body {
    Unknown, // Requirement of `Default` impl, required by YaDeserialize

    #[yaserde(prefix = "tds")]
    AddIPAddressFilterResponse(super::AddIPAddressFilterResponse),
    #[yaserde(prefix = "tds")]
	AddScopesResponse(super::AddScopesResponse),
    #[yaserde(prefix = "tds")]
	CreateCertificateResponse(super::CreateCertificateResponse),
    #[yaserde(prefix = "tds")]
	CreateDot1XConfigurationResponse(super::CreateDot1XConfigurationResponse),
    #[yaserde(prefix = "tds")]
	CreateStorageConfigurationResponse(super::CreateStorageConfigurationResponse),
    #[yaserde(prefix = "tds")]
	CreateUsersResponse(super::CreateUsersResponse),
    #[yaserde(prefix = "tds")]
	DeleteCertificatesResponse(super::DeleteCertificatesResponse),
    #[yaserde(prefix = "tds")]
	DeleteDot1XConfigurationResponse(super::DeleteDot1XConfigurationResponse),
    #[yaserde(prefix = "tds")]
	DeleteGeoLocationResponse(super::DeleteGeoLocationResponse),
    #[yaserde(prefix = "tds")]
	DeleteStorageConfigurationResponse(super::DeleteStorageConfigurationResponse),
    #[yaserde(prefix = "tds")]
	DeleteUsersResponse(super::DeleteUsersResponse),
    #[yaserde(prefix = "tds")]
	GetAccessPolicyResponse(super::GetAccessPolicyResponse),
    #[yaserde(prefix = "tds")]
	GetAuthFailureWarningConfigurationResponse(super::GetAuthFailureWarningConfigurationResponse),
    #[yaserde(prefix = "tds")]
	GetAuthFailureWarningOptionsResponse(super::GetAuthFailureWarningOptionsResponse),
    #[yaserde(prefix = "tds")]
	GetCACertificatesResponse(super::GetCACertificatesResponse),
    #[yaserde(prefix = "tds")]
	GetCapabilitiesResponse(super::GetCapabilitiesResponse),
    #[yaserde(prefix = "tds")]
	GetCertificateInformationResponse(super::GetCertificateInformationResponse),
    #[yaserde(prefix = "tds")]
	GetCertificatesResponse(super::GetCertificatesResponse),
    #[yaserde(prefix = "tds")]
	GetCertificatesStatusResponse(super::GetCertificatesStatusResponse),
    #[yaserde(prefix = "tds")]
	GetClientCertificateModeResponse(super::GetClientCertificateModeResponse),
    #[yaserde(prefix = "tds")]
	GetDNSResponse(super::GetDNSResponse),
    #[yaserde(prefix = "tds")]
	GetDPAddressesResponse(super::GetDPAddressesResponse),
    #[yaserde(prefix = "tds")]
	GetDeviceInformationResponse(super::GetDeviceInformationResponse),
    #[yaserde(prefix = "tds")]
	GetDiscoveryModeResponse(super::GetDiscoveryModeResponse),
    #[yaserde(prefix = "tds")]
	GetDot11CapabilitiesResponse(super::GetDot11CapabilitiesResponse),
    #[yaserde(prefix = "tds")]
	GetDot11StatusResponse(super::GetDot11StatusResponse),
    #[yaserde(prefix = "tds")]
	GetDot1XConfigurationResponse(super::GetDot1XConfigurationResponse),
    #[yaserde(prefix = "tds")]
	GetDot1XConfigurationsResponse(super::GetDot1XConfigurationsResponse),
    #[yaserde(prefix = "tds")]
	GetDynamicDNSResponse(super::GetDynamicDNSResponse),
    #[yaserde(prefix = "tds")]
	GetEndpointReferenceResponse(super::GetEndpointReferenceResponse),
    #[yaserde(prefix = "tds")]
	GetGeoLocationResponse(super::GetGeoLocationResponse),
    #[yaserde(prefix = "tds")]
	GetHostnameResponse(super::GetHostnameResponse),
    #[yaserde(prefix = "tds")]
	GetIPAddressFilterResponse(super::GetIPAddressFilterResponse),
    #[yaserde(prefix = "tds")]
	GetNTPResponse(super::GetNTPResponse),
    #[yaserde(prefix = "tds")]
	GetNetworkDefaultGatewayResponse(super::GetNetworkDefaultGatewayResponse),

    #[yaserde(prefix = "tds")]
	GetNetworkInterfacesResponse(super::GetNetworkInterfacesResponse),

    #[yaserde(prefix = "tds")]
	GetNetworkProtocolsResponse(super::GetNetworkProtocolsResponse),
    #[yaserde(prefix = "tds")]
	GetPasswordComplexityConfigurationResponse(super::GetPasswordComplexityConfigurationResponse),
    #[yaserde(prefix = "tds")]
	GetPasswordComplexityOptionsResponse(super::GetPasswordComplexityOptionsResponse),
    #[yaserde(prefix = "tds")]
	GetPasswordHistoryConfigurationResponse(super::GetPasswordHistoryConfigurationResponse),
    #[yaserde(prefix = "tds")]
	GetPkcs10RequestResponse(super::GetPkcs10RequestResponse),
    #[yaserde(prefix = "tds")]
	GetRelayOutputsResponse(super::GetRelayOutputsResponse),
    #[yaserde(prefix = "tds")]
	GetRemoteDiscoveryModeResponse(super::GetRemoteDiscoveryModeResponse),
    #[yaserde(prefix = "tds")]
	GetRemoteUserResponse(super::GetRemoteUserResponse),
    #[yaserde(prefix = "tds")]
	GetScopesResponse(super::GetScopesResponse),
    #[yaserde(prefix = "tds")]
	GetServiceCapabilitiesResponse(super::GetServiceCapabilitiesResponse),

    //NB: wild stab in the dark
    #[yaserde(prefix = "tds")]
	GetServicesResponse(super::GetServicesResponse),

    #[yaserde(prefix = "tds")]
	GetStorageConfigurationResponse(super::GetStorageConfigurationResponse),
    #[yaserde(prefix = "tds")]
	GetStorageConfigurationsResponse(super::GetStorageConfigurationsResponse),
    #[yaserde(prefix = "tds")]
	GetSystemBackupResponse(super::GetSystemBackupResponse),
    #[yaserde(prefix = "tds")]
	GetSystemDateAndTimeResponse(super::GetSystemDateAndTimeResponse),
    #[yaserde(prefix = "tds")]
	GetSystemLogResponse(super::GetSystemLogResponse),
    #[yaserde(prefix = "tds")]
	GetSystemSupportInformationResponse(super::GetSystemSupportInformationResponse),
    #[yaserde(prefix = "tds")]
	GetSystemUrisResponse(super::GetSystemUrisResponse),
    #[yaserde(prefix = "tds")]
	GetUsersResponse(super::GetUsersResponse),
    #[yaserde(prefix = "tds")]
	GetWsdlUrlResponse(super::GetWsdlUrlResponse),
    #[yaserde(prefix = "tds")]
	GetZeroConfigurationResponse(super::GetZeroConfigurationResponse),
    #[yaserde(prefix = "tds")]
	LoadCACertificatesResponse(super::LoadCACertificatesResponse),
    #[yaserde(prefix = "tds")]
	LoadCertificateWithPrivateKeyResponse(super::LoadCertificateWithPrivateKeyResponse),
    #[yaserde(prefix = "tds")]
	LoadCertificatesResponse(super::LoadCertificatesResponse),
    #[yaserde(prefix = "tds")]
	RemoveIPAddressFilterResponse(super::RemoveIPAddressFilterResponse),
    #[yaserde(prefix = "tds")]
	RemoveScopesResponse(super::RemoveScopesResponse),
    #[yaserde(prefix = "tds")]
	RestoreSystemResponse(super::RestoreSystemResponse),
    #[yaserde(prefix = "tds")]
	ScanAvailableDot11NetworksResponse(super::ScanAvailableDot11NetworksResponse),
    #[yaserde(prefix = "tds")]
	SendAuxiliaryCommandResponse(super::SendAuxiliaryCommandResponse),
    #[yaserde(prefix = "tds")]
	SetAccessPolicyResponse(super::SetAccessPolicyResponse),
    #[yaserde(prefix = "tds")]
	SetAuthFailureWarningConfigurationResponse(super::SetAuthFailureWarningConfigurationResponse),
    #[yaserde(prefix = "tds")]
	SetCertificatesStatusResponse(super::SetCertificatesStatusResponse),
    #[yaserde(prefix = "tds")]
	SetClientCertificateModeResponse(super::SetClientCertificateModeResponse),
    #[yaserde(prefix = "tds")]
	SetDNSResponse(super::SetDNSResponse),
    #[yaserde(prefix = "tds")]
	SetDPAddressesResponse(super::SetDPAddressesResponse),
    #[yaserde(prefix = "tds")]
	SetDiscoveryModeResponse(super::SetDiscoveryModeResponse),
    #[yaserde(prefix = "tds")]
	SetDot1XConfigurationResponse(super::SetDot1XConfigurationResponse),
    #[yaserde(prefix = "tds")]
	SetDynamicDNSResponse(super::SetDynamicDNSResponse),
    #[yaserde(prefix = "tds")]
	SetGeoLocationResponse(super::SetGeoLocationResponse),
    #[yaserde(prefix = "tds")]
	SetHostnameFromDHCPResponse(super::SetHostnameFromDHCPResponse),
    #[yaserde(prefix = "tds")]
	SetHostnameResponse(super::SetHostnameResponse),
    #[yaserde(prefix = "tds")]
	SetIPAddressFilterResponse(super::SetIPAddressFilterResponse),
    #[yaserde(prefix = "tds")]
	SetNTPResponse(super::SetNTPResponse),
    #[yaserde(prefix = "tds")]
	SetNetworkDefaultGatewayResponse(super::SetNetworkDefaultGatewayResponse),
    #[yaserde(prefix = "tds")]
	SetNetworkInterfacesResponse(super::SetNetworkInterfacesResponse),
    #[yaserde(prefix = "tds")]
	SetNetworkProtocolsResponse(super::SetNetworkProtocolsResponse),
    #[yaserde(prefix = "tds")]
	SetPasswordComplexityConfigurationResponse(super::SetPasswordComplexityConfigurationResponse),
    #[yaserde(prefix = "tds")]
	SetPasswordHistoryConfigurationResponse(super::SetPasswordHistoryConfigurationResponse),
    #[yaserde(prefix = "tds")]
	SetRelayOutputSettingsResponse(super::SetRelayOutputSettingsResponse),
    #[yaserde(prefix = "tds")]
	SetRelayOutputStateResponse(super::SetRelayOutputStateResponse),
    #[yaserde(prefix = "tds")]
	SetRemoteDiscoveryModeResponse(super::SetRemoteDiscoveryModeResponse),
    #[yaserde(prefix = "tds")]
	SetRemoteUserResponse(super::SetRemoteUserResponse),
    #[yaserde(prefix = "tds")]
	SetScopesResponse(super::SetScopesResponse),
    #[yaserde(prefix = "tds")]
	SetStorageConfigurationResponse(super::SetStorageConfigurationResponse),
    #[yaserde(prefix = "tds")]
	SetSystemDateAndTimeResponse(super::SetSystemDateAndTimeResponse),
    #[yaserde(prefix = "tds")]
	SetSystemFactoryDefaultResponse(super::SetSystemFactoryDefaultResponse),
    #[yaserde(prefix = "tds")]
	SetUserResponse(super::SetUserResponse),
    #[yaserde(prefix = "tds")]
	SetZeroConfigurationResponse(super::SetZeroConfigurationResponse),
    #[yaserde(prefix = "tds")]
	StartFirmwareUpgradeResponse(super::StartFirmwareUpgradeResponse),
    #[yaserde(prefix = "tds")]
	StartSystemRestoreResponse(super::StartSystemRestoreResponse),
    #[yaserde(prefix = "tds")]
	SystemRebootResponse(super::SystemRebootResponse),
    #[yaserde(prefix = "tds")]
	UpgradeSystemFirmwareResponse(super::UpgradeSystemFirmwareResponse)
}

impl Default for Body {
    fn default() -> Self {
        Body::Unknown
    }
}