[package]
name = "a12n"
version = "0.1.0"
edition = "2021"
description = "ONVIF authentication"

[dependencies]
base64 = "0.13.0"
sha1 = "0.10.5"
yaserde.workspace = true
yaserde_derive.workspace = true
