[package]
name = "xop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
validate = { path = "../../validate" }
xml-rs = "0.8.3"
yaserde = "0.7.1"
yaserde_derive = "0.7.1"
