[package]
name = "xop"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
validate = { path = "../../validate" }
xml-rs = "0.8.3"
yaserde = "0.7.1"
yaserde_derive = "0.7.1"
